### PR TITLE
postoga: the post-processing pipeline

### PR DESCRIPTION
**Pull request by alejandrogzi**
Hi @MichaelHiller and @kirilenkobm,

After our last contact in #91 I have worked with some ideas about a post-processing pipeline. This PR adds [postoga](https://github.com/alejandrogzi/postoga), a post-processing pipeline that implements: 

1) dependencies (python pkgs + rust binaries: [bed2gtf](https://github.com/alejandrogzi/bed2gtf), which you already knew about, and [bed2gff](https://github.com/alejandrogzi/bed2gff), a new program I developed that easily converts .bed files to .gff3 files also written in Rust) 
2) user-specific filtering of the query annotation (by class (I,UL,L,...), by relationship (o2o, o2m, m2m, ...) and confidence (0 - 1), and any given combination [null is also available, were the user simply does not want to filter it])
3) conversion of bed to gtf/gff (user can specify if is converted to gtf or to gff; also postoga extracts all available transcripts and creates a new file called "isoforms.txt" that ensures the completion of the conversion without errors)
4) automatically estimates assembly quality by the ancestral placental mammal gene dataset (postoga reimplements all the features of `TOGA_assemblyStats.py`)
5) if user want to merge files from different assemblies of the same species or haplotype-resolved assemblies, postoga implements a branch mode called "haplotype" (`postoga haplotype`), that quickly does the job (this reimplementation also fixes some structural/syntax problems of `TOGA_assemblyStats.py merge` and makes it more efficient (without nested loops)
6) besides the .log file produced called `postoga.log`, where a lot of stats and comments are clearly specified to the user; postoga makes a graphical report, plotting (until v.0.6.0-devel) 5 figures (this is going to increase at least to two pages) that allows the user to nicely visualize the information TOGA provided about their assemblies. This report includes information like: class/relation/confidence of the base `query_annotation.bed`; the class/relation/confidence of the `filtered.bed`; the comparison between the amount of annotated genes in their assembly and 509 mammals (Fig.5 TOGA paper) with also the options to specify if the user want to be compare against a "human" background, "mouse" background of if the user assembly is a bird species, against a "chicken" background; the summarized gene classes of the `query_annotation.bed` OR `filtered.bed` (if user filters the file, then this info is about the filtered file); and finally, a comparison of the %ancestral missing vs %ancestral inactivated between user assembly and other 509 mammals (Fig. 6. TOGA paper).

This PR also deleted the submodule `bed2gtf`, because `postoga` directly handles the binary installation and takes care of any configuring step of rust/cargo (it also offers an option to build binaries, with bed2gtf and bed2gff as submodules of postoga).

If you would like to knwo how does postoga works or its status (a lot of features are under development) checkout [postoga](https://github.com/alejandrogzi). Let me know if you test it or if are there any bugs/errors/problems. Also would be a lot of help if you could give some feedback or desired features or comments. At the bottom of the repo I have listed some of the things I will implement (including ortholog length calculation of query, alignment stats, and more).

Best,
Alejandro

### CODE REVIEW

**Comment by MichaelHiller** [comment]
Excellent !! 
I'll ask the lab to test it. 

Thx a lot !

**Comment by kirilenkobm** [comment]
Hi @alejandrogzi, thanks for organizing this =). Since it doesn’t affect the core TOGA functionality, I'll merge it into the master right away. @MichaelHiller, there's another pull request [https://github.com/hillerlab/TOGA/pull/105](https://github.com/hillerlab/TOGA/pull/105) which I've merged into a separate branch [https://github.com/hillerlab/TOGA/tree/test-pr-105](https://github.com/hillerlab/TOGA/tree/test-pr-105). I'll test it out; it should only affect the parallelization, not the "scientific part". Just a heads-up that this change is on the way.

**Comment by mahajrod** [comment]
Hi @alejandrogzi , @MichaelHiller and @kirilenkobm,

I just tried to run posTOGA on the TOGA output and it didn't work. I had solved first issue, but was stuck on the second one. 

Issues: 
1. posTOGA expects  files **orthology_scores.tsv** to be in the **temp/**  subdirectory, whereas TOGA keeps it in the main directory

2. postTOGA requires file  transcript_quality.tsv (also in the **temp/** subdir), but TOGA doesn't generate it... According to  the test example of  posTOGA file should look like:

`
Projection_ID	confidence_level
ENST00000355624.10	high_confidence
ENST00000418232.77	high_confidence
ENST00000590873.104	high_confidence
ENST00000502994.4	high_confidence
ENST00000567195.12	partial
`

In modules of TOGA I found script **get_transcripts_quality.py** , which is not used by TOGA. At least grep-ing the whole TOGA repo shows only initialization of path to this script. 

`
./modules/get_transcripts_quality.py -h

usage: get_transcripts_quality.py [-h] [--hq_threshold HQ_THRESHOLD] meta_data orthology_scores output

positional arguments:
  meta_data             Exons meta data
  orthology_scores      Orthology scores file
  output                Save output to

options:
  -h, --help            show this help message and exit
  --hq_threshold HQ_THRESHOLD, --hqt HQ_THRESHOLD
                        Orthology score for high-confidence transcripts
`
Is it the right script to generate transcript_quality.tsv ? 
If yes what input (meta_data and orthology_scores ) does it expect?
Is **orthology_scores** a **orthology_scores.tsv** file?
What is the recommended value for --hq_threshold ?

Best regards,
Sergei

**Comment by kirilenkobm** [comment]
@mahajrod 

Thank you for your feedback. 

Regarding the placement of `orthology_scores.tsv`, I'm considering moving it to the temp directory as it might be more appropriate there. However, I'm open to suggestions if you have any insights on this.

Indeed, I recently disabled the the generation of `transcript_quality.tsv`because it was not essential for the core functionality.

This is how `get_transcripts_quality.py` can be used:

```txt
(venv2) ➜  TOGA git:(master) ✗ modules/get_transcripts_quality.py micro_test_out/temp/exons_meta_data.tsv micro_test_out/orthology_scores.tsv micro_test_out/test.tsv
(venv2) ➜  TOGA git:(master) ✗ cat micro_test_out/test.tsv 
Projection_ID   confidence_level
ENST00000262455.1169    partial
ENST00000259400.1169    high_confidence
ENST00000618101.1169    high_confidence
```

@alejandrogzi could you please check how easy it is to move `get_transcripts_quality.py` functionality to the `postoga` pipeline?

**Comment by mahajrod** [comment]
@kirilenkobm

You answered much faster than I expected )
I already figured out how to run this script, but faced additional issues with running posTOGA...
For example, it fails with error if was run not from installation folder,  git command from README doesnt pull submodules, and commands used to run bed2gff and bed2gtf are incorrect at least for current versions.

After some testing,  I'll submit a pull request to postTOGA with fixes.

**Comment by mahajrod** [comment]
Regarding the location of  orthology_scores.tsv.

Storing any files that might be used by downstream tools in folders named like **temp** or **tmp** is a dangerous practice. Just the name of such folders provokes user to consider it as redundant after the successful run.  And a person may just delete it and loose the data necessary for next steps...

**Comment by kirilenkobm** [comment]
@mahajrod you're right.
The main problem is to figure out what might be used and what theoretically should not :)

**Comment by mahajrod** [comment]
@kirilenkobm 
Absolutely agree :) That's why I use "intermediate" or similar instead of "temp" in such cases.

Regarding the posTOGA. I finally forced it to run on my data (annotation of mammal with reference gff from NCBI) and submitted the PR.
But result is a bit ironic. bed2gff fails on working with my TOGA output)
Issue, most likely, is related to isoforms.txt.
I see a lot of rows at the end of file with first column empty. 
Trying to fix it and understand why it have happened (file is attached)...


[isoforms.txt.gz](https://github.com/hillerlab/TOGA/files/13627907/isoforms.txt.gz)

**Comment by MichaelHiller** [comment]
I would put any file that contains potentially useful but final data in the main dir. Or a dir called data/ or something. 
But temp indicates that all files in there are no longer important when the TOGA run is done.

**Comment by mahajrod** [comment]
Then it is an issue of postTOGA. It seeks for files in temp folder.

Just found that there are also a file **query_isoforms.tsv** in main dir (postTOGA tries to use **temp/isoforms.txt**).
It looks normal - no rows with first column empty, but **query_annotation.bed** contains all that isoform ids with missing gene ids  from  **temp/isoforms.txt**...  as result, bed2gff fails again.

[query_isoforms.tsv.gz](https://github.com/hillerlab/TOGA/files/13628056/query_isoforms.tsv.gz)

**Comment by alejandrogzi** [comment]
Hi all, 

Thanks @mahajrod for catch this! I have been quite distracted by other projects going on and could not update all the advances I have made to posTOGA. Your feedback is well appreciated. 

@MichaelHiller, @kirilenkobm I will make some time to update and keep improving posTOGA.

Best,
Alejandro

**Pull request merged**
